### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ivankravets**
- This library in Web Registry: http://platformio.org/#!/lib/show/572/StandardCplusplus
- Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)
- Library Manager:  http://docs.platformio.org/en/latest/librarymanager/index.html

### CODE REVIEW

**Comment by jcoliz** [comment]
Cherry-picked these individually. Thanks for the contribution!

**Comment by maniacbug** [comment]
Cherry-picked these individually. Thanks for the contribution!

**Comment by ivankravets** [comment]
@maniacbug, thanks for merging `library.json`. Could you also merge these changes https://github.com/maniacbug/StandardCplusplus/pull/35 ?

You can close that PR but reflect the changes in the repository. It is up to you. Thanks again!

**Comment by maniacbug** [comment]
@ivankravets You bet. Thanks for contributing!

**Pull request closed without merging**
